Lab4/zooShop/cart/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Lab4/zooShop/order/urls.py
from . import views
from django.urls import path

app_name = 'order'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

Lab4/zooShop/zooShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('zooShop_app.urls', namespace='zooShop_app')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Lab4/zooShop/zooShop_app/urls.py
from django.urls import path
from . import views

app_name = 'zooShop_app'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('products', views.ProductsList, name = 'products'),
    path('products/<int:id>', views.product_detail, name = 'product_details'),
    path('<str:type>', views.ProductsList,name='product_list_by_type'),
    path('register/', views.RegisterUser.as_view(), name = 'register'),
    path('logout/', views.logout_user, name = 'logout'),
    path('login/', views.LoginUser.as_view(), name = 'login'),
    path("create/", views.product_create, name='create'),
    path("products/edit/<int:id>/", views.product_edit),
    path("products/delete/<int:id>/", views.product_delete),

]

Lab4/zooShop/cart/models.py
from django.db import models

# Create your models here.

Lab4/zooShop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 5)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

Lab4/zooShop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from zooShop_app.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django.core.exceptions import PermissionDenied

@require_POST
def cart_add(request, product_id):
    if not request.user.is_authenticated:
        raise PermissionDenied("No acsess")

    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    if not request.user.is_authenticated:
        raise PermissionDenied("No acsess")

    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    if not request.user.is_authenticated:
        raise PermissionDenied("No acsess")
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

Lab4/zooShop/cart/templates/cart/detail.html
{% extends "base.html" %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
        <tr>
            <th></th>
            <th>Product||</th>
            <th>Quantity||</th>
            <th>Remove||</th>
            <th>Unit price||</th>
            <th>Price||</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{{ product.photo.url }}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url 'cart:cart_remove' product.id %}">Remove</a></td>
                    <td class="num">{{ item.cost }}</td>
                    <td class="num">{{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td><h4>Total</h4></td>
            <td colspan="4"></td>
            <td class="num"><h4>{{ cart.get_total_price }}</h4></td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <h4><a href="{% url 'zooShop_app:products' %}" class="button light">Continue shopping</a>
            <a href="{% url 'order:order_create' %}">Checkout</a></h4>
    </p>
{% endblock %}