Lab4/zooShop/cart/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Lab4/zooShop/zooShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('zooShop_app.urls', namespace='zooShop_app')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Lab4/zooShop/zooShop_app/urls.py
from django.urls import path
from . import views

app_name = 'zooShop_app'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('products', views.ProductsList, name = 'products'),
    path('products/<int:id>', views.product_detail, name = 'product_details'),
    path('<str:type>', views.ProductsList,name='product_list_by_type'),
    path('register/', views.RegisterUser.as_view(), name = 'register'),
    path('logout/', views.logout_user, name = 'logout'),
    path('login/', views.LoginUser.as_view(), name = 'login'),
    path("create/", views.product_create, name='create'),
    path("products/edit/<int:id>/", views.product_edit),
    path("products/delete/<int:id>/", views.product_delete),

]

Lab4/zooShop/zooShop_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Product(models.Model):
    vendor_code = models.CharField(max_length = 20, help_text="Enter vendor code")
    amount = models.PositiveIntegerField(default=0)
    name = models.CharField(max_length = 20, help_text="Enter name")
    description = models.TextField(help_text="Enter description")
    cost = models.IntegerField()
    product_type = models.ForeignKey('ProductType', on_delete=models.SET_NULL, null=True, help_text="Choose product type")
    provider = models.ForeignKey('Provider', on_delete=models.SET_NULL, null=True, help_text="Choose provider")
    photo = models.ImageField(upload_to='images', blank=True)

    def __str__(self) :
        return f'{self.name}, {self.cost}'

    def get_absolute_url(self):
        return reverse('zooShop_app:product_details', args=[str(self.id)])

class Provider(models.Model):
    name = models.CharField(max_length=20, help_text="Enter name")
    address = models.CharField(max_length=20, help_text="Enter owner")
    phone_number = models.CharField(max_length=20, help_text="Enter phone number")

    def __str__(self):
        return f'{self.name}, {self.address}, {self.phone_number}'

class ProductType(models.Model):
    designation = models.CharField(max_length=20, help_text="Enter type")

    def __str__(self):
        return self.designation

    def get_absolute_url(self):
        return reverse('zooShop_app:product_list_by_type', args=[str(self.designation)])

class Client(models.Model):
    first_name = models.CharField(max_length=20, help_text='Enter first name')
    last_name = models.CharField(max_length=20, help_text='Enter last name')
    date_of_birth = models.DateField(help_text="Enter date of birth")
    email = models.EmailField(help_text="Enter email")
    phone_number = models.CharField(max_length=15, help_text='Enter phone number')

    def __str__(self):
        return f'{self.first_name}, {self.last_name}'

    def get_absolute_url(self):
        return reverse('client-detail', args=[str(self.id)])

Lab4/zooShop/zooShop_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.validators import RegexValidator
from datetime import date
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm
from .models import Product


def validate_age(value):
    today = date.today()
    age = today.year - value.year - int((today.month, today.day) < (value.month, value.day))
    if int(age) < 18:
        raise ValidationError("You must be over 18 years old")


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='login', widget=forms.TextInput(attrs={'class': 'form-input'}))

    first_name = forms.CharField(label='first name', widget=forms.TextInput(attrs={'class': 'form-input'}))
    last_name = forms.CharField(label='last name', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(label='email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    date_birthday = forms.DateField(label='date of birth', widget=forms.DateInput(attrs={'class': 'form-input'}),
                                    validators=[validate_age])
    phone_number = forms.CharField(label='phone number', widget=forms.TextInput(attrs={'class': 'form-input'}),
                                   validators=[RegexValidator(
                                       regex=r'^(\+375 \(29\) [0-9]{3}-[0-9]{2}-[0-9]{2})$',
                                       message='Format +375 (29) XXX-XX-XX',
                                   )])
    password1 = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='repeat password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = (
        'username', 'first_name', 'last_name', 'email', 'date_birthday', 'phone_number', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='login', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))


class ProductForm(forms.ModelForm):
    vendor_code = forms.CharField(label='vendor_code', widget=forms.TextInput(attrs={'class': 'form-input'}))
    name = forms.CharField(label='name', widget=forms.TextInput(attrs={'class': 'form-input'}))
    amount = forms.IntegerField(label='amount', widget=forms.TextInput(attrs={'class': 'form-input'}))
    cost = forms.IntegerField(label='cost', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = Product
        fields = ['vendor_code', 'amount', 'name', 'description', 'cost', 'product_type', 'provider', 'photo']

Lab4/zooShop/zooShop_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import logout, login
from .models import *
from django.views.generic import DetailView, CreateView
from django.urls import reverse_lazy
from zooShop_app.forms import RegisterUserForm, LoginUserForm, ProductForm
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.http import HttpResponseNotFound
from cart.forms import CartAddProductForm
import requests


# Create your views here.

def index(request):
    products = Product.objects.all()[:3]
    joke = requests.get('https://official-joke-api.appspot.com/jokes/random').json()
    cat = requests.get('https://catfact.ninja/fact').json()
    return render(request, 'index.html',
                  context={'products': products, 'joke': joke['setup'] + joke['punchline'], 'cat': cat['fact']})


def ProductsList(request, type=None):
    products = Product.objects.all()
    product_type = None
    product_types = ProductType.objects.all()
    sort_type_price = request.GET.get('sort_price')

    if str(sort_type_price) == 'ascending':
        products = products.order_by('cost')

    elif str(sort_type_price) == 'descending':
        products = products.order_by('-cost')

    if type:
        product_type = get_object_or_404(ProductType, designation=type)
        products = products.filter(product_type=product_type)
        print(product_type)

    return render(request, 'products.html', {'products': products, 'product_type': product_type, 'product_types': product_types})


class ProductDetailView(DetailView):
    model = Product
    cart_product_form = CartAddProductForm()

    template_name = 'product_details.html'


def product_detail(request, id):
    product = get_object_or_404(Product, id=id)
    cart_product_form = CartAddProductForm()

    return render(request,
                  'product_details.html',
                  {'product': product, 'cart_product_form': cart_product_form})


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'register.html'
    success_url = reverse_lazy('zooShop_app:login')

    def form_valid(self, form):
        user = form.save()

        Client.objects.create(first_name=form.cleaned_data['first_name'],
                              last_name=form.cleaned_data['last_name'],
                              date_of_birth=form.cleaned_data['date_birthday'],
                              email=form.cleaned_data['email'],
                              phone_number=form.cleaned_data['phone_number']).save()

        login(self.request, user)
        return redirect('zooShop_app:index')


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'login.html'
    success_url = reverse_lazy('zooShop_app:login')

    def get_success_url(self):
        return reverse_lazy('zooShop_app:index')


def logout_user(request):
    logout(request)
    return redirect('zooShop_app:index')


def product_create(request):
    form = ProductForm()

    if request.method == "POST":
        product = Product.objects.create(vendor_code=request.POST.get('vendor_code'),
                                 amount=request.POST.get('amount'),
                                 name=request.POST.get('name'),
                                 description=request.POST.get('description'),
                                 cost=request.POST.get('cost'),
                                 product_type=ProductType.objects.get(id=request.POST.get('product_type')),
                                 provider=Provider.objects.get(id=request.POST.get('provider')),
                                 photo=request.FILES.get('photo')),


    else:
        return render(request, "create_product.html", {"form": form})
    return HttpResponseRedirect("/")


def product_edit(request, id):
    try:
        product = Product.objects.get(id=id)

        form = ProductForm(initial={'vendor_code': product.vendor_code, 'amount': product.amount,'name': product.name,
                                'description': product.description, 'cost': product.cost,
                                'product_type': product.product_type, 'provider': product.provider,
                                'photo': product.photo})

        if request.method == "POST":
            product.vendor_code = request.POST.get('vendor_code')
            product.amount = request.POST.get('amount')
            product.name = request.POST.get('name')
            product.description = request.POST.get('description')
            product.cost = request.POST.get('cost')
            product.product_type = ProductType.objects.get(id=request.POST.get('product_type'))
            product.provider = Provider.objects.get(id=request.POST.get('provider'))
            product.photo = request.FILES.get('photo')
            product.save()
            return HttpResponseRedirect("/")
        else:
            return render(request, "edit_product.html", {"product": product, 'form': form})

    except product.DoesNotExist:
        return HttpResponseNotFound("<h2>Product not found :(</h2>")


def product_delete(request, id):
    try:
        product = Product.objects.get(id=id)
        product.delete()
        return HttpResponseRedirect("/")
    except product.DoesNotExist:
        return HttpResponseNotFound("<h2>product not found</h2>")

Lab4/zooShop/zooShop_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<head>
   {% block title %}{%endblock%}
</head>
<body>

<div>
  <ul>
    <li><a href="{% url 'zooShop_app:index' %}">Home</a></li>
    <li><a href="{% url 'zooShop_app:products' %}">All Products</a></li>
</ul>
</div>


<div id="subheader">
  <div class="cart">
      {%if user.is_authenticated%}
      {% with total_items=cart|length %}
          {% if cart|length > 0 %}
              Your cart:
              <a href="{% url 'cart:cart_detail' %}">
                  {{ total_items }} item{{ total_items|pluralize }},
                  ${{ cart.get_total_price }}
              </a>
          {% else %}
              Your cart is empty.
          {% endif %}
      {% endwith %}
      {%endif%}
      {% if user.is_authenticated %}
              |{{ user.username }}|
              <a href="{% url 'zooShop_app:logout' %}">Out</a>
              {% else %}
              <a href="{% url 'zooShop_app:login' %}">Sign up</a>
              <a href="{% url 'zooShop_app:register' %}">Sign in</a>
              {% endif %}
  </div>
</div>

{%if request.user.is_staff%}

<div><a href="{% url 'zooShop_app:create'%}">add new product</a></div>
{%endif%}

    {%block content%}
    
    {%endblock%}
</body>
</html>

Lab4/zooShop/zooShop_app/templates/create_product.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Create</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        {%for f in form%}
        <p><label for="{{f.id_for_label}}">{{f.label}}: </label>{{f}}</p>
        <div>{{f.errors}}</div>
        {%endfor%}
        <input type="submit" value="Save" >
    </form>
</body>
</html>

Lab4/zooShop/zooShop_app/templates/edit_product.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Edit</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        {%for f in form%}
        <p><label for="{{f.id_for_label}}">{{f.label}}: </label>{{f}}</p>
        <div>{{f.errors}}</div>
        {%endfor%}
        <input type="submit" value="Save" >
    </form>
</body>
</html>

Lab4/zooShop/zooShop_app/templates/index.html
{% extends "base.html" %}

{% block title %}

<title>Main Page</title>

{% endblock %}

{% block content %}

{% for product in products%}
<li>    
    <img src="{{product.photo.url}}">
   <a href="{% url 'zooShop_app:product_details' product.id %}">{{product.name}}, {{product.cost}}</a>
</li>


{% endfor %}
{%if user.is_authenticated%}
<h3>Joke 4u - {{joke}} </h3>
<h3>cat fact - {{cat}}</h3>
{%endif%}
{% endblock %}

Lab4/zooShop/zooShop_app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
</head>
<body>
    <form method="post">
        {%csrf_token%}
        <div>{{form.non_field_errors}}</div>
        {%for f in form%}
        <p><label for="{{f.id_for_label}}">{{f.label}}: </label>{{f}}</p>
        <div>{{f.errors}}</div>
        {%endfor%}
        <button type="submit">Sign in</button>
    </form>
</body>
</html>

Lab4/zooShop/zooShop_app/templates/product_details.html
{% extends "base.html" %}

{% block title %}

<title>Product Details Page</title>

{% endblock %}

{% block content %}
{%if request.user.is_staff%}

<div>
    <a href="edit/{{product.id}}/">Edit product</a>
    <a href="delete/{{product.id}}">Delete product</a>

</div>
{%endif%}
<img src="{{product.photo.url}}">
<ul>
<li>{{product.vendor_code}}</li>
<li>{{product.amount}}</li>
<li>{{product.name}}</li>
<li>{{product.description}}</li>
<li>{{product.cost}}</li>
<li>{{product.product_type}}</li>
<li>{{product.provider}}</li>

{%if user.is_authenticated%}
<form action="{% url 'cart:cart_add' product.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" value="Add to cart">
</form>
{%endif%}

</ul>
{% endblock %}

Lab4/zooShop/zooShop_app/templates/products.html
{% extends "base.html" %}

{% block title %}

<title>Products Page</title>

{% endblock %}

{% block content %}


<ul> 

<form action="{{ request.get_full_path }}" method="get">
   <button type="submit" name="sort_price" value="ascending">Sort up by price</button>
   <button type="submit" name="sort_price" value="descending">Sort down by price</button>
</form>

<div id="sidebar">
   <h3>Products</h3>
   <ul>
       
       {% for c in product_types %}
           <li {% if product_type.designation == c.designation %}class="selected" {% endif %}>
               <a href="{{ c.get_absolute_url }}">{{ c.designation }}</a>
           </li>
       {% endfor %}
   </ul>
</div>

{% for product in products %}
<li>    
   <img src="{{product.photo.url}}">

   <a href="{% url 'zooShop_app:product_details' product.id %}">{{product.name}}, {{product.cost}}</a>
</li>

{% endfor %}

</ul>
{% endblock %}

Lab4/zooShop/zooShop_app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration Page</title>
</head>
<body>
    <form method="post">
        {%csrf_token%}
        {%for f in form%}
        <p><label for="{{f.id_for_label}}">{{f.label}}: </label>{{f}}</p>
        <div>{{f.errors}}</div>
        {%endfor%}
        <button type="submit">Registration</button>
    </form>
</body>
</html>